language: python

python:
 - "3.5"

install:
 - pip install -r requirements.txt
 - pip install coveralls

script:
 - coverage run --source=Cocoamphoactate.tests.test_friends_pending_rest manage.py test
 - python3 manage.py test Cocoamphoactate.tests.test_recommendations
 - python3 manage.py test Cocoamphoactate.tests.test_search_rest
 - python3 manage.py test Cocoamphoactate.tests.test_user_rest

 after_success:
 - coveralls
