# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-16 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='url',
            field=models.CharField(default='https://az853139.vo.msecnd.net/static/images/not-found.png', max_length=200),
        ),
    ]
