# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-30 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cocoamphoactate', '0006_auto_20161130_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.CharField(default='none', max_length=1000),
        ),
        migrations.AddField(
            model_name='reviews',
            name='review',
            field=models.CharField(default='none', max_length=1000),
        ),
        migrations.AddField(
            model_name='score',
            name='score',
            field=models.FloatField(default=5, max_length=10),
        ),
    ]
