# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-14 10:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cocoamphoactate', '0007_auto_20161130_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorites',
            name='game',
        ),
        migrations.RemoveField(
            model_name='favorites',
            name='user',
        ),
        migrations.RemoveField(
            model_name='friends',
            name='user_one',
        ),
        migrations.RemoveField(
            model_name='friends',
            name='user_two',
        ),
        migrations.RemoveField(
            model_name='friendspending',
            name='user_one',
        ),
        migrations.RemoveField(
            model_name='friendspending',
            name='user_two',
        ),
        migrations.RemoveField(
            model_name='gamelib',
            name='game',
        ),
        migrations.RemoveField(
            model_name='gamelib',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='game',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='user',
        ),
        migrations.RemoveField(
            model_name='score',
            name='game_id',
        ),
        migrations.RemoveField(
            model_name='score',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Favorites',
        ),
        migrations.DeleteModel(
            name='Friends',
        ),
        migrations.DeleteModel(
            name='FriendsPending',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='GameLib',
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
